[functions.push-sync]
verify_jwt = false

[functions.calculate-club-ranking]
verify_jwt = false

[functions.poll-eventor-publication]
verify_jwt = false

[functions.sverigelistan-latest]
verify_jwt = false

[functions.notify-feedback]
verify_jwt = false

[functions.person-search]
verify_jwt = false

[functions.poll-friend-activity]
verify_jwt = false

[functions.poll-live-friends]
verify_jwt = false
